version: '3.8'

services:
  # 1. Database
  db:
    image: postgres:15-alpine
    container_name: asset_db_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}      # <--- Reads from .env
      POSTGRES_PASSWORD: ${DB_PASSWORD} # <--- Reads from .env
      POSTGRES_DB: ${DB_NAME}        # <--- Reads from .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Backend
  backend:
    build: ./asset-control-service
    container_name: asset_backend_container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      
      # Pass JWT secrets too!
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
    depends_on:
      db:
        condition: service_healthy

  # 3. Frontend
  frontend:
    build: ./asset-frontend
    container_name: asset_frontend_container
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  postgres_data:
